services:
  nica-pay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nica-pay
    env_file:
      - .env 
    volumes:
      - .:/app
    working_dir: /app
    command: ["python3", "src/bot.py"]
